import { readFileSync, writeFileSync, copyFileSync, existsSync, mkdirSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';
import { homedir } from 'os';
import { getPlatform, type Platform } from '../utils/platform.js';

// Resolve dist/hooks/ from this CLI's package location
const __dirname = dirname(fileURLToPath(import.meta.url));
const DIST_HOOKS = join(__dirname, 'hooks');

const BUILT_IN_HOOKS = [
  { src: 'post-agent.cjs', dest: 'post-agent.js', event: 'PostToolUse' },
  { src: 'subagent-start.cjs', dest: 'subagent-start.js', event: 'SubagentStart' },
  { src: 'subagent-stop.cjs', dest: 'subagent-stop.js', event: 'SubagentStop' },
  { src: 'runner.cjs', dest: 'runner.js', event: null },
];

/** Compute all init-relevant paths for a given platform (always fresh, ignores module cache). */
function getPaths(platform: Platform) {
  const home = homedir();
  const base = platform === 'opencode'
    ? join(home, '.config', 'opencode')
    : join(home, '.claude');

  const hooksDir = join(base, 'hooks', 'chains');
  return {
    baseDir: base,
    hooksDir,
    customHooksDir: join(hooksDir, 'custom'),
    chainsDir: join(base, 'chains'),
    settingsFile: join(base, 'settings.json'),
    hooksConfigFile: join(hooksDir, 'hooks-config.yaml'),
  };
}

export function initCommand(flags: Record<string, string>): void {
  // Determine platform — explicit flag wins over auto-detection
  const platformFlag = flags['platform'] as Platform | undefined;
  const platform: Platform = (platformFlag === 'opencode' || platformFlag === 'claude')
    ? platformFlag
    : getPlatform();

  const P = getPaths(platform);

  console.log(`Initializing brainbrew for ${platform}...\n`);

  // 1. Create directories
  const dirs = [P.baseDir, P.hooksDir, P.customHooksDir, P.chainsDir];
  for (const dir of dirs) {
    if (!existsSync(dir)) {
      mkdirSync(dir, { recursive: true });
      console.log(`  Created: ${dir}`);
    }
  }

  // 2. Copy compiled hooks from this CLI package → hooks/chains/
  let installed = 0;
  for (const hook of BUILT_IN_HOOKS) {
    const src = join(DIST_HOOKS, hook.src);
    const dest = join(P.hooksDir, hook.dest);

    if (existsSync(src)) {
      copyFileSync(src, dest);
      installed++;
      console.log(`  Installed: ${hook.dest}`);
    } else {
      console.log(`  Warning: ${hook.src} not found in package — skipping`);
    }
  }
  console.log(`  ${installed}/${BUILT_IN_HOOKS.length} hooks installed`);

  // 3. Generate hooks-config.yaml (preserve existing custom hooks)
  const existingCustom = existsSync(P.hooksConfigFile)
    ? parseExistingCustomHooks(readFileSync(P.hooksConfigFile, 'utf-8'))
    : {};

  const config = generateConfig(existingCustom);
  writeFileSync(P.hooksConfigFile, config);
  console.log(`  Written: hooks-config.yaml`);

  // 4. Register hooks with the active platform
  if (platform === 'opencode') {
    installOpenCodePlugin(P.hooksDir);
  } else {
    if (flags['skip-settings'] !== 'true') {
      updateSettings(P.settingsFile, P.hooksDir, P.hooksConfigFile);
    }
  }

  // 5. Register MCP server
  registerMCPServer(platform, P.baseDir);

  console.log(`\nDone. Hooks are ready at ${P.hooksDir}`);
  console.log('\nAll 22 hook events supported.');
  console.log('Add custom hooks: brainbrew hook scaffold --name <name> --event <event>');
}

function generateConfig(existingCustom: Record<string, string[]>): string {
  const lines = ['# Brainbrew hook configuration', '# Generated by: brainbrew init', '', 'hooks:'];

  // Built-in events with default hooks
  const defaults: Record<string, string> = {
    PostToolUse: 'post-agent.js',
    SubagentStart: 'subagent-start.js',
    SubagentStop: 'subagent-stop.js',
  };

  for (const [event, hookFile] of Object.entries(defaults)) {
    lines.push(`  ${event}:`);
    lines.push(`    - ${hookFile}`);
    // Append custom hooks for this event
    if (existingCustom[event]) {
      for (const custom of existingCustom[event]) {
        lines.push(`    - ${custom}`);
      }
    }
  }

  // Events that only have custom hooks (no built-in)
  for (const [event, customs] of Object.entries(existingCustom)) {
    if (defaults[event]) continue; // already handled
    lines.push(`  ${event}:`);
    for (const custom of customs) {
      lines.push(`    - ${custom}`);
    }
  }

  return lines.join('\n') + '\n';
}

function parseExistingCustomHooks(content: string): Record<string, string[]> {
  const result: Record<string, string[]> = {};
  let currentEvent = '';

  for (const line of content.split('\n')) {
    const eventMatch = line.match(/^\s{2}(\S+):$/);
    if (eventMatch) {
      currentEvent = eventMatch[1];
      continue;
    }
    const itemMatch = line.match(/^\s{4}-\s+(.+)/);
    if (itemMatch && currentEvent) {
      const hook = itemMatch[1];
      // Only keep custom hooks — built-in will be re-added
      if (hook.includes('custom/')) {
        if (!result[currentEvent]) result[currentEvent] = [];
        result[currentEvent].push(hook);
      }
    }
  }
  return result;
}

// ─── Claude Code: patch settings.json ────────────────────────────────────────

function updateSettings(settingsFile: string, hooksDir: string, hooksConfigFile: string): void {
  if (!existsSync(settingsFile)) {
    console.log('\n  Warning: settings.json not found. Skipping.');
    return;
  }

  const settings = JSON.parse(readFileSync(settingsFile, 'utf-8'));
  const runnerPath = join(hooksDir, 'runner.js');

  // Remove old hooks (ours or legacy)
  const isOurHook = (h: any) =>
    h?.hooks?.[0]?.command?.includes('hooks/chains/') ||
    h?.hooks?.[0]?.command?.includes('brainbrew') ||
    h?.hooks?.[0]?.command?.includes('.claude-chain');

  const cleanHooks = (arr: unknown[]) =>
    (arr || []).filter((h: any) => !isOurHook(h));

  settings.hooks = settings.hooks || {};

  // Read config to know which events have hooks
  const configContent = existsSync(hooksConfigFile) ? readFileSync(hooksConfigFile, 'utf-8') : '';
  const events = [...configContent.matchAll(/^\s{2}(\S+):$/gm)].map(m => m[1]);

  for (const event of events) {
    const existing = cleanHooks(settings.hooks[event] || []);
    const matcher = event === 'PostToolUse' ? 'Agent' : '.*';

    existing.push({
      matcher,
      hooks: [{ type: 'command', command: `node ${runnerPath} ${event}` }],
    });

    settings.hooks[event] = existing;
  }

  writeFileSync(settingsFile, JSON.stringify(settings, null, 2));
  console.log(`  Updated: ${settingsFile} (${events.length} events)`);
}

// ─── OpenCode: generate plugin file ──────────────────────────────────────────

function installOpenCodePlugin(hooksDir: string): void {
  const pluginDir = join(homedir(), '.config', 'opencode', 'plugins');
  const pluginFile = join(pluginDir, 'brainbrew.js');
  const runnerPath = join(hooksDir, 'runner.js');

  if (!existsSync(pluginDir)) {
    mkdirSync(pluginDir, { recursive: true });
  }

  // Generate a JS plugin that invokes the runner script for each hook event.
  // OpenCode plugins export a hooks object with event handler functions.
  // Each handler invokes the brainbrew runner via Node child_process,
  // passing the event name as an argument (same pattern as Claude Code's
  // settings.json hook commands).
  //
  // NOTE: Verify the exact OpenCode plugin export shape against
  // https://opencode.ai/docs/plugins/ if hook events are not firing.
  const pluginContent = `/**
 * Brainbrew DevKit - OpenCode Plugin
 * Auto-generated by: brainbrew init --platform opencode
 *
 * Invokes the brainbrew runner script for each hook event.
 * Runner path: ${runnerPath}
 */

import { execSync } from 'child_process';

function runBrainbrew(event, payload) {
  try {
    execSync(\`node "${runnerPath}" \${event}\`, {
      input: JSON.stringify(payload),
      encoding: 'utf-8',
      stdio: ['pipe', 'inherit', 'inherit'],
      timeout: 90000,
    });
  } catch {
    // Non-zero exit from hooks is handled by runner.cjs internally
  }
}

export const id = 'brainbrew';

export const hooks = {
  postToolUse: (payload) => runBrainbrew('PostToolUse', payload),
  subagentStart: (payload) => runBrainbrew('SubagentStart', payload),
  subagentStop: (payload) => runBrainbrew('SubagentStop', payload),
  sessionStart: (payload) => runBrainbrew('SessionStart', payload),
  sessionEnd: (payload) => runBrainbrew('SessionEnd', payload),
};
`;

  writeFileSync(pluginFile, pluginContent);
  console.log(`  Created: ${pluginFile}`);
}

// ─── MCP server registration (both platforms) ─────────────────────────────────

function registerMCPServer(platform: Platform, baseDir: string): void {
  // Resolve MCP server binary from this CLI's dist/ directory
  const mcpServerPath = join(__dirname, '..', 'mcp', 'mcp-server.cjs');
  if (!existsSync(mcpServerPath)) {
    console.log('  Warning: mcp-server.cjs not found — skipping MCP registration');
    return;
  }

  if (platform === 'opencode') {
    registerOpenCodeMCP(mcpServerPath);
  } else {
    registerClaudeCodeMCP(mcpServerPath, baseDir);
  }
}

function registerClaudeCodeMCP(mcpServerPath: string, baseDir: string): void {
  const mcpConfigPath = join(baseDir, 'mcp.json');

  let existing: Record<string, unknown> = {};
  if (existsSync(mcpConfigPath)) {
    try {
      existing = JSON.parse(readFileSync(mcpConfigPath, 'utf-8'));
    } catch { /* use empty object */ }
  }

  const servers = (existing.mcpServers ?? {}) as Record<string, unknown>;
  servers['brainbrew'] = {
    command: 'node',
    args: [mcpServerPath],
  };
  existing.mcpServers = servers;

  writeFileSync(mcpConfigPath, JSON.stringify(existing, null, 2));
  console.log(`  Updated MCP config: ${mcpConfigPath}`);
}

function registerOpenCodeMCP(mcpServerPath: string): void {
  const opencodeConfigPath = join(homedir(), '.config', 'opencode', 'opencode.json');

  let existing: Record<string, unknown> = {};
  if (existsSync(opencodeConfigPath)) {
    try {
      existing = JSON.parse(readFileSync(opencodeConfigPath, 'utf-8'));
    } catch { /* use empty object */ }
  }

  // Deep-merge into mcp — non-destructive, preserves existing entries
  // OpenCode MCP format: mcp.{name} (no servers nesting), command is array, environment not env
  const mcp = (existing.mcp ?? {}) as Record<string, unknown>;
  mcp['brainbrew'] = {
    type: 'local',
    command: ['node', mcpServerPath],
    environment: {
      OPENCODE_PLUGIN_ROOT: dirname(mcpServerPath),
    },
  };
  existing.mcp = mcp;

  const dir = dirname(opencodeConfigPath);
  if (!existsSync(dir)) mkdirSync(dir, { recursive: true });

  writeFileSync(opencodeConfigPath, JSON.stringify(existing, null, 2));
  console.log(`  Updated MCP config: ${opencodeConfigPath}`);
}
