import { readFileSync, writeFileSync, copyFileSync, existsSync, mkdirSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';
import {
  CLAUDE_DIR,
  HOOKS_DIR,
  CUSTOM_HOOKS_DIR,
  CHAINS_DIR,
  SETTINGS_FILE,
  HOOKS_CONFIG_FILE,
} from '../utils/paths.js';

// Resolve dist/hooks/ from this CLI's package location
const __dirname = dirname(fileURLToPath(import.meta.url));
const DIST_HOOKS = join(__dirname, 'hooks');

const BUILT_IN_HOOKS = [
  { src: 'post-agent.cjs', dest: 'post-agent.js', event: 'PostToolUse' },
  { src: 'subagent-start.cjs', dest: 'subagent-start.js', event: 'SubagentStart' },
  { src: 'subagent-stop.cjs', dest: 'subagent-stop.js', event: 'SubagentStop' },
  { src: 'runner.cjs', dest: 'runner.js', event: null },
];

export function initCommand(flags: Record<string, string>): void {
  console.log('Initializing brainbrew...\n');

  // 1. Create directories
  const dirs = [CLAUDE_DIR, HOOKS_DIR, CUSTOM_HOOKS_DIR, CHAINS_DIR];
  for (const dir of dirs) {
    if (!existsSync(dir)) {
      mkdirSync(dir, { recursive: true });
      console.log(`  Created: ${dir}`);
    }
  }

  // 2. Copy compiled hooks from this CLI package → ~/.claude/hooks/chains/
  let installed = 0;
  for (const hook of BUILT_IN_HOOKS) {
    const src = join(DIST_HOOKS, hook.src);
    const dest = join(HOOKS_DIR, hook.dest);

    if (existsSync(src)) {
      copyFileSync(src, dest);
      installed++;
      console.log(`  Installed: ${hook.dest}`);
    } else {
      console.log(`  Warning: ${hook.src} not found in package — skipping`);
    }
  }
  console.log(`  ${installed}/${BUILT_IN_HOOKS.length} hooks installed`);

  // 3. Generate hooks-config.yaml (preserve existing custom hooks)
  const existingCustom = existsSync(HOOKS_CONFIG_FILE)
    ? parseExistingCustomHooks(readFileSync(HOOKS_CONFIG_FILE, 'utf-8'))
    : {};

  const config = generateConfig(existingCustom);
  writeFileSync(HOOKS_CONFIG_FILE, config);
  console.log(`  Written: hooks-config.yaml`);

  // 4. Update ~/.claude/settings.json
  if (flags['skip-settings'] !== 'true') {
    updateSettings();
  }

  console.log('\nDone. Hooks are ready at ~/.claude/hooks/chains/');
  console.log('\nAll 22 Claude Code events supported.');
  console.log('Add custom hooks: brainbrew hook scaffold --name <name> --event <event>');
}

function generateConfig(existingCustom: Record<string, string[]>): string {
  const lines = ['# Brainbrew hook configuration', '# Generated by: brainbrew init', '', 'hooks:'];

  // Built-in events with default hooks
  const defaults: Record<string, string> = {
    PostToolUse: 'post-agent.js',
    SubagentStart: 'subagent-start.js',
    SubagentStop: 'subagent-stop.js',
  };

  for (const [event, hookFile] of Object.entries(defaults)) {
    lines.push(`  ${event}:`);
    lines.push(`    - ${hookFile}`);
    // Append custom hooks for this event
    if (existingCustom[event]) {
      for (const custom of existingCustom[event]) {
        lines.push(`    - ${custom}`);
      }
    }
  }

  // Events that only have custom hooks (no built-in)
  for (const [event, customs] of Object.entries(existingCustom)) {
    if (defaults[event]) continue; // already handled
    lines.push(`  ${event}:`);
    for (const custom of customs) {
      lines.push(`    - ${custom}`);
    }
  }

  return lines.join('\n') + '\n';
}

function parseExistingCustomHooks(content: string): Record<string, string[]> {
  const result: Record<string, string[]> = {};
  let currentEvent = '';

  for (const line of content.split('\n')) {
    const eventMatch = line.match(/^\s{2}(\S+):$/);
    if (eventMatch) {
      currentEvent = eventMatch[1];
      continue;
    }
    const itemMatch = line.match(/^\s{4}-\s+(.+)/);
    if (itemMatch && currentEvent) {
      const hook = itemMatch[1];
      // Only keep custom hooks — built-in will be re-added
      if (hook.includes('custom/')) {
        if (!result[currentEvent]) result[currentEvent] = [];
        result[currentEvent].push(hook);
      }
    }
  }
  return result;
}

function updateSettings(): void {
  if (!existsSync(SETTINGS_FILE)) {
    console.log('\n  Warning: ~/.claude/settings.json not found. Skipping.');
    return;
  }

  const settings = JSON.parse(readFileSync(SETTINGS_FILE, 'utf-8'));
  const runnerPath = join(HOOKS_DIR, 'runner.js');

  // Remove old hooks (ours or legacy)
  const isOurHook = (h: any) =>
    h?.hooks?.[0]?.command?.includes('hooks/chains/') ||
    h?.hooks?.[0]?.command?.includes('brainbrew') ||
    h?.hooks?.[0]?.command?.includes('.claude-chain');

  const cleanHooks = (arr: unknown[]) =>
    (arr || []).filter((h: any) => !isOurHook(h));

  settings.hooks = settings.hooks || {};

  // Read config to know which events have hooks
  const configContent = existsSync(HOOKS_CONFIG_FILE) ? readFileSync(HOOKS_CONFIG_FILE, 'utf-8') : '';
  const events = [...configContent.matchAll(/^\s{2}(\S+):$/gm)].map(m => m[1]);

  for (const event of events) {
    const existing = cleanHooks(settings.hooks[event] || []);
    const matcher = event === 'PostToolUse' ? 'Agent|task|Task' : '.*';

    existing.push({
      matcher,
      hooks: [{ type: 'command', command: `node ${runnerPath} ${event}` }],
    });

    settings.hooks[event] = existing;
  }

  writeFileSync(SETTINGS_FILE, JSON.stringify(settings, null, 2));
  console.log(`  Updated: ~/.claude/settings.json (${events.length} events)`);
}
